<?php

namespace Data\Doctrine\Proxy\__CG__\Data\Doctrine\Main;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ContentNew extends \Data\Doctrine\Main\ContentNew implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     *
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'id', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'pattern', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'language', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'type', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'access', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'updatedAt', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'content', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'auditor', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'author', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'content2'];
        }

        return ['__isInitialized__', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'id', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'pattern', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'language', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'type', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'access', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'updatedAt', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'content', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'auditor', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'author', '' . "\0" . 'Data\\Doctrine\\Main\\ContentNew' . "\0" . 'content2'];
    }

    /**
     *
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ContentNew $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     *
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }


    /**
     * {@inheritDoc}
     */
    public function setPattern($pattern)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPattern', [$pattern]);

        return parent::setPattern($pattern);
    }

    /**
     * {@inheritDoc}
     */
    public function getPattern()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPattern', []);

        return parent::getPattern();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccess($access)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccess', [$access]);

        return parent::setAccess($access);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccess', []);

        return parent::getAccess();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent2(\Data\Doctrine\Main\Content $content2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent2', [$content2]);

        return parent::setContent2($content2);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent2', []);

        return parent::getContent2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor(\Data\Doctrine\Main\User $author = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', [$author]);

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', []);

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuditor(\Data\Doctrine\Main\User $auditor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuditor', [$auditor]);

        return parent::setAuditor($auditor);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuditor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuditor', []);

        return parent::getAuditor();
    }

}
