<?php namespace Defines;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-28 at 09:36:02.
 */
class ExtensionTest extends \Tests\Simple
{

    /**
     * @covers Defines\Extension::getDefault
     */
    public function testGetDefault()
    {
        $this->assertEquals(Extension::HTML, Extension::getDefault());
    }

    /**
     * @covers Defines\Extension::getList
     */
    public function testGetList()
    {
        $aList = Extension::getList();
        $this->assertInternalType('array', $aList);
        $this->assertEquals(7, sizeof($aList));
        $this->assertContains(Extension::HTML, $aList);
        $this->assertContains(Extension::JSON, $aList);
        $this->assertContains(Extension::PNG, $aList);
        $this->assertContains(Extension::RSS, $aList);
        $this->assertContains(Extension::TXT, $aList);
        $this->assertContains(Extension::XML, $aList);
        $this->assertContains(Extension::AMP, $aList);
    }
}
