<?php namespace Defines;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-28 at 09:36:02.
 */
class LanguageTest extends \Tests\Simple
{

    /**
     * @covers Defines\Extension::getDefault
     */
    public function testGetDefault()
    {
        $this->assertEquals(Language::BE, Language::getDefault());
    }

    /**
     * @covers Defines\Extension::getList
     */
    public function testGetList()
    {
        $aList = Language::getList();
        $this->assertInternalType('array', $aList);
        $this->assertEquals(6, sizeof($aList));
        $this->assertContains(Language::BE, $aList);
        $this->assertContains(Language::DE, $aList);
        $this->assertContains(Language::EN, $aList);
        $this->assertContains(Language::FR, $aList);
        $this->assertContains(Language::RU, $aList);
        $this->assertContains(Language::UK, $aList);
    }
}
