<?php namespace Engine\Response\Meta;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-23 at 14:24:58.
 */
class StyleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Style
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new Style;
    }

    /**
     * @covers Engine\Response\Meta\Style::setMedia
     * @covers Engine\Response\Meta\Style::__construct
     */
    public function testSetMedia()
    {
        $this->assertInstanceOf('\Engine\Response\Meta\Style', $this->object->setMedia('all'));
    }

    /**
     * @covers Engine\Response\Meta\Style::isEqual
     */
    public function testIsEqual()
    {
        $o = new Style('test');
        $this->assertTrue($o->isEqual($o));
        $o2 = new Style('', 'test');
        $this->assertFalse($o->isEqual($o2));
        $this->assertFalse($o2->isEqual($o2));
    }
}
