<?php namespace Modules\Dev\Access;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 08:34:39.
 */
class ModelTest extends \Tests\Simple
{

    /**
     * @var Model
     */
    protected $object;

    protected function setUp()
    {
        parent::setUp();
        $this->object = new Model;
    }

    /**
     * @covers Modules\Dev\Access\Model::getAccessList
     * @covers Modules\Dev\Access\Model::defineList
     */
    public function testGetAccessList()
    {
        $this->assertInternalType('array', $this->object->getAccessList());
    }
}
