<?php namespace Engine\Response;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-12 at 08:42:39.
 */
class JsonLdTest extends \Tests\Simple
{

    /**
     * @var JsonLd
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new JsonLd([]);
    }

    /**
     * @covers Engine\Response\JsonLd::add
     * @covers Engine\Response\JsonLd::focus
     */
    public function testFocus()
    {
        $this->object->append(['test' => 1]);
        $this->object->append(['test' => 2]);
        $this->object->append(['test' => 3]);
        $this->assertEquals(['test' => 2], $this->object->focus(1));
        $this->assertEquals(null, $this->object->focus(100));
    }
}
