<?php namespace System\Converter\Helper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-21 at 14:00:37.
 */
class LaTeXTest extends \Tests\Simple
{

    /**
     * @var LaTeX
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new LaTeX;
    }


    /**
     * @covers System\Converter\Helper\LaTeX::compile
     */
    public function testDisableCompile()
    {
        $text = "<textarea>\\table{begin}<br />
| \\quote{1} | test | sample |* 2 | <br />
| summary ***| <br />
\\table{end}<br />
<br />
\\quote{324}
</textarea>";
        $result = $this->object->compile($text);
        $this->assertEquals($result, $text);
    }


    /**
     * @covers System\Converter\Helper\LaTeX::compile
     */
    public function testCompile()
    {
        $text = "\\table{begin}<br />"
            . "\n| \\quote{1} | test | sample |* 2 | <br />"
            . "\n| summary ***| <br />"
            . "\n\\table{end}<br />"
            . "\n<br />"
            . "\n\\quote{324}";
        $result = $this->object->compile($text);
        // echo "\n\n", $result, "\n\n";
        $sample = '<table class="el_border" border="1">'
        . "\n"
        . '    <tr class=""><td class="el_border indent"><blockquote>'
        . "\n"
        . '    Не знойдзена</blockquote></td><td class="el_border indent">test</td><td class="el_border indent">sample</td>'
        . '<td class="el_border indent" rowspan="2">2</td></tr><tr class="">'
        . '<td class="el_border indent" colspan="4">summary</td></tr></table><br />'
        . "\n<br />\n"
        . '<blockquote>' . "\n"
        . '    Не знойдзена</blockquote>';
        $this->assertEquals($result, $sample);
    }

    /**
     * @covers System\Converter\Helper\LaTeX::get
     */
    public function testGet()
    {
        return;
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
